### ISSUE TITLE
Should no-equal-arguments trigger on double.infinity?

### ISSUE THREAD

**Issue by PiN73** [dart-code-checker/dart-code-metrics#327]
```dart
class MyWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return OverflowBox(
      maxWidth: double.infinity,
      maxHeight: double.infinity,
      child: Container(),
    );
  }
}
```

> warning: The argument has already been passed. (no-equal-arguments at ...)

**Comment by incendial** [comment]
Looks like it's an exceptional case when equal arguments are expected and correct, because if you replace `double.infinity` with literals, like 10.0, it would still be correct, but the rule will trigger. Same goes for a const variable used for both `maxWidth` and `maxHeight`.

So the only solution I can suggest right now is to use ignores `// ignore: no-equal-arguments`.

**Comment by incendial** [comment]
Actually, this looks like a fix to the problem your pointed out https://github.com/dart-code-checker/dart-code-metrics/issues/339.
