### ISSUE TITLE
[Feature request] Configuration presets

### ISSUE THREAD

**Issue by roman-petrov** [dart-code-checker/dart-code-metrics#459]
At the moment to configure dart code metrics users generally should follow [Configuration](https://dartcodemetrics.dev/docs/getting-started/configuration) guide and enable/configure rules they need in `analysis_options.yaml`.

For common Dart linter rules, there are many packages with rule presets, including official `lints` & `flutter_lints` packages. A similar mechanism exists in popular [eslint](https://eslint.org/) JavaScript linter: there is an ability to [extend configuration files](https://eslint.org/docs/user-guide/configuring/configuration-files#extending-configuration-files) with built-in presets `eslint:all` & `eslint:recommended`.

So we might consider implementing a similar solution to simplify quick start for new users. 

I also think that having this may affect & improve upgrade flow.  When a new rule is introduced in a new version:
* Currently should manually add it into `analysis_options.yaml` if they like this new rule **and** if they read changelogs. 
* Using up-to-date preset with all rules enabled will always promote the new rule to the codebase. So users will have to fix all violations without reading changelogs or just disable this new rule.

Personally, I prefer the second approach.

IMHO this is just a "nice to have" feature request so I am not proposing any implementation design right now. We can discuss this in detail if we get some interest in this feature from the community.

**Comment by incendial** [comment]
Good news is that we already support overriding / merging mechanism for the analysis_options config. So, we just need to add the presets. But I personally think it's really inefficient to add ALL rules to a `preset_all`, especially, since we have rules for DartAngular. I think we should create several presets for flutter and dart, like flutter_all, flutter_recommended, dart_all, dart_recommended and these presets will not include rules for DartAngular and Intl. WDYT?

**Comment by roman-petrov** [comment]
I completely agree with you, I had the same thoughts. Nothing more to say :)

**Comment by incendial** [comment]
Available in 4.21.0 🚀
